title:             Bence goes to Germany
email:             akbence007@gmail.com
description:       Erasmus+ in Erlangen
author:            Bence Ágocsi Kiss
baseurl:           "/bencegoestogermany"
url:               "http://akbence.github.io"

# Social Profiles
 
github_username:   akbence
facebook_username: bence.ak
instagram_username: bence_little

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
